#! /bin/sh -f
#
#  Install script for Gemini timelib library
#

host=`hostname`
if [ "`egrep $host /etc/hosts | egrep '^10\.'`" -ne "" ]; then
    site=MK;
else
    site=CP;
fi

slalib_dir=/gemini/GEM8.5/slalib/slalib

applSetup.pl -T mv167 -T ppc604_long -I src -I startup -d $slalib_dir -S $site $1 > $2 2>&1

gmake >> $2 2>&1

exit 0
