# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions

include Target.include
include .applTop/config/CONFIG

# External libraries on which this directory is dependent.
# DEPLIBS	=

# User compiler and loader flags
USR_CFLAGS   = -K PIC
# USR_INCLUDES =
# USR_LDFLAGS  =
# USR_LDLIBS   =

# Add the source code files to this variable. The default has all .c files 
SRCS.c	= $(wildcard ../*.c) 

# Add the object files in one of these two variables. 
# LIBOBJS += test.o
LIBOBJS	=  timeInit.o timeNow.o timeNowC.o timeNowD.o timeNowR.o timeNowT.o \
           timeOffline.o timeOffset.o timeTai2raw.o timeThenC.o timeThenD.o \
           timeThenR.o timeThenT.o timeRaw2tai.o timePrint.o

# Standard macros for files which are to be built and installed.
# PROD (products) and SCRIPTS are installed in INSTALL_BIN
PROD	= $(patsubst %.o, %, $(OBJS))
SCRIPTS	=

# LIBNAME is installed in INSTALL_LIB
LIBNAME	= libtime.a

# INC is installed in INSTALL_INCLUDE
INC	=

# MAN1 is installed in INSTALL_MAN/man1
MAN1	=

# DOCS are installed in INSTALL_DOC
DOCS	=

# DATA are installed in INSTALL_DATA
DATA	= $(wildcard ../resource.def)

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)

TARGETS =

# Rules for building targets
include .applTop/config/RULES.Build

# There is no product rule, but one can be added or modified if required
#$(PROD): $(OBJS) $(DEPLIBS)
#	$(RM) $@
#	$(LINK.c) -o $@ $(OBJS) $(LDLIBS)
